Repository alibaba/sentinel-cpp, pull requests merged in 2019-05, with the labels that each got.

#1 Fix CI build failed due to bazel version
  .travis.yml
  bazel/copts.bzl
Labels: bug

#3 Add unittests for data source extension
  sentinel-datasource-extension/datasource/BUILD
  sentinel-datasource-extension/datasource/abstract_readable_data_source.h
  sentinel-datasource-extension/datasource/abstract_readable_data_source_unittests.cc
  sentinel-datasource-extension/datasource/converter.h
  sentinel-datasource-extension/datasource/readable_data_source.h
  sentinel-datasource-extension/test/mock/datasource/BUILD
  sentinel-datasource-extension/test/mock/datasource/mock.cc
  sentinel-datasource-extension/test/mock/datasource/mock.h
Labels: kind/enhancement

#6 Enhancement interface availability and fix compile error
  .travis.yml
  WORKSPACE
  bazel/copts.bzl
  sentinel-core/common/entry_result.h
  sentinel-core/flow/default_traffic_shaping_calculator.h
  sentinel-core/flow/flow_rule.h
  sentinel-core/flow/flow_rule_checker.cc
  sentinel-core/flow/flow_rule_manager.cc
  sentinel-core/init/init_target.h
  sentinel-core/property/dynamic_sentinel_property.h
  sentinel-core/property/sentinel_property.h
  sentinel-core/public/sph_u.cc
  sentinel-core/public/sph_u.h
  sentinel-core/public/sph_u_test.cc
  sentinel-core/slot/base/default_slot_chain_impl.h
  sentinel-core/slot/base/slot_base.h
  sentinel-core/slot/log_slot.h
  sentinel-core/slot/resource_node_builder_slot.h
  sentinel-core/slot/resource_node_builder_slot_test.cc
  sentinel-core/slot/statistic_slot.h
  sentinel-core/statistic/base/leap_array.h
  sentinel-core/statistic/base/metric_bucket.h
  sentinel-core/utils/time_utils.cc
  sentinel-datasource-extension/datasource/abstract_readable_data_source.h
  sentinel-datasource-extension/datasource/converter.h
  sentinel-datasource-extension/test/mock/datasource/mock.h
Labels: kind/enhancement

#7 Solve CI failures by updating the bazel version
  .travis.yml
Labels: kind/bug

#4 Httpserver metric
  sentinel-core/config/local_config.h
  sentinel-core/log/BUILD
  sentinel-core/log/log_base.cc
  sentinel-core/log/log_base.h
  sentinel-core/log/log_base_test.cc
  sentinel-core/log/metric_reader.cc
  sentinel-core/log/metric_reader.h
  sentinel-core/log/metric_reader_test.cc
  sentinel-core/log/metric_searcher.cc
  sentinel-core/log/metric_searcher.h
  sentinel-core/log/metric_searcher_test.cc
  sentinel-core/log/metric_test_utils.h
  sentinel-core/log/metric_writer.cc
  sentinel-core/log/metric_writer.h
  sentinel-core/log/metric_writer_test.cc
  sentinel-core/log/record_log.cc
  sentinel-core/log/record_log.h
  sentinel-core/log/record_log_unittests.cc
  sentinel-core/transport/command/BUILD
  sentinel-core/transport/command/command_handler.h
  sentinel-core/transport/command/command_request.cc
  sentinel-core/transport/command/command_request.h
  sentinel-core/transport/command/command_request_test.cc
  sentinel-core/transport/command/command_response.h
  sentinel-core/transport/command/http_command_center.cc
  sentinel-core/transport/command/http_command_center.h
  sentinel-core/transport/command/http_command_utils.cc
  sentinel-core/transport/command/http_command_utils.h
  sentinel-core/transport/command/http_server.cc
  sentinel-core/transport/command/http_server.h
  sentinel-core/transport/common/BUILD
  sentinel-core/transport/common/event_loop_thread.cc
  sentinel-core/transport/common/event_loop_thread.h
  sentinel-core/transport/common/event_loop_thread_test.cc
  sentinel-core/utils/BUILD
  sentinel-core/utils/file_utils.cc
  sentinel-core/utils/file_utils.h
Labels: kind/feature

#5 Fix the concurrent problem of caching the last token result in StatsSlot
  sentinel-core/common/BUILD
  sentinel-core/common/entry_context.h
  sentinel-core/slot/base/default_slot_chain_impl.cc
  sentinel-core/slot/base/rule_checker_slot.h
  sentinel-core/slot/base/slot.h
  sentinel-core/slot/base/stats_slot.h
  sentinel-core/slot/statistic_slot.cc
  sentinel-core/slot/statistic_slot_test.cc
Labels: kind/bug
