Repository alibaba/sentinel-cpp, pull requests merged in 2019-06, with the labels that each got.

#11 Add on/off switch command handler and fix global chain problem
  sentinel-core/common/BUILD
  sentinel-core/common/constants.h
  sentinel-core/common/entry.h
  sentinel-core/common/global_status.cc
  sentinel-core/common/global_status.h
  sentinel-core/config/local_config.cc
  sentinel-core/flow/flow_rule_manager.cc
  sentinel-core/log/metric/BUILD
  sentinel-core/log/metric/metric_reader_test.cc
  sentinel-core/log/metric/metric_writer.cc
  sentinel-core/property/dynamic_sentinel_property.h
  sentinel-core/public/BUILD
  sentinel-core/public/sph_u.cc
  sentinel-core/slot/BUILD
  sentinel-core/slot/global_slot_chain.cc
  sentinel-core/slot/global_slot_chain.h
  sentinel-core/transport/command/BUILD
  sentinel-core/transport/command/command_handler.h
  sentinel-core/transport/command/command_response.h
  sentinel-core/transport/command/handler/BUILD
  sentinel-core/transport/command/handler/fetch_cluster_node_handler.cc
  sentinel-core/transport/command/handler/fetch_cluster_node_handler.h
  sentinel-core/transport/command/handler/fetch_metric_log_handler.cc
  sentinel-core/transport/command/handler/fetch_metric_log_handler.h
  sentinel-core/transport/command/handler/get_switch_status_handler.cc
  sentinel-core/transport/command/handler/get_switch_status_handler.h
  sentinel-core/transport/command/handler/set_switch_status_handler.cc
  sentinel-core/transport/command/handler/set_switch_status_handler.h
  sentinel-core/transport/command/handler/set_switch_status_handler_test.cc
  sentinel-core/transport/command/http_command_center.cc
  sentinel-core/transport/command/http_command_center.h
  sentinel-core/transport/command/http_server_init_target.cc
Labels: kind/enhancement

#12 Refactor logger module
  examples/sentinel-cpp/BUILD
  examples/sentinel-cpp/basic_concurrency_limit.cc
  examples/sentinel-cpp/basic_qps_limit.cc
  sentinel-core/config/BUILD
  sentinel-core/config/local_config.cc
  sentinel-core/flow/BUILD
  sentinel-core/flow/flow_rule_manager.cc
  sentinel-core/log/BUILD
  sentinel-core/log/logger.cc
  sentinel-core/log/logger.h
  sentinel-core/log/logger_unittests.cc
  sentinel-core/log/metric/BUILD
  sentinel-core/log/metric/metric_writer.cc
  sentinel-core/log/record_log.cc
  sentinel-core/log/record_log.h
  sentinel-core/log/record_log_unittests.cc
  sentinel-core/statistic/node/BUILD
  sentinel-core/statistic/node/resource_node_storage.cc
  sentinel-core/transport/command/BUILD
  sentinel-core/transport/command/handler/set_switch_status_handler.cc
  sentinel-core/transport/command/http_server.cc
  sentinel-core/utils/BUILD
  sentinel-core/utils/macros.h
Labels: kind/enhancement

#13 Add LogSlot for logging blocked requests and refactor logger
  examples/sentinel-cpp/basic_concurrency_limit.cc
  examples/sentinel-cpp/basic_qps_limit.cc
  sentinel-core/common/constants.h
  sentinel-core/log/BUILD
  sentinel-core/log/block/BUILD
  sentinel-core/log/block/block_log_task.cc
  sentinel-core/log/block/block_log_task.h
  sentinel-core/log/block/block_log_task_test.cc
  sentinel-core/log/logger.cc
  sentinel-core/log/logger.h
  sentinel-core/log/logger_unittests.cc
  sentinel-core/slot/BUILD
  sentinel-core/slot/global_slot_chain.h
  sentinel-core/slot/log_slot.cc
  sentinel-core/slot/log_slot.h
  sentinel-core/statistic/base/BUILD
  sentinel-core/statistic/base/stat_config_manager.cc
  sentinel-core/statistic/node/resource_node_storage.cc
Labels: kind/feature

#14 Fix compile warning
  sentinel-core/common/tracer.cc
  sentinel-core/flow/default_traffic_shaping_calculator.cc
  sentinel-core/flow/flow_rule_checker.cc
  sentinel-core/flow/flow_rule_manager.cc
  sentinel-core/flow/flow_slot.cc
  sentinel-core/flow/throttling_traffic_shaping_checker.cc
  sentinel-core/log/logger.h
  sentinel-core/slot/base/rule_checker_slot.h
  sentinel-core/slot/global_slot_chain.cc
  sentinel-core/slot/global_slot_chain.h
  sentinel-core/slot/log_slot.cc
  sentinel-core/slot/log_slot.h
  sentinel-core/slot/resource_node_builder_slot.cc
  sentinel-core/slot/statistic_slot.cc
  sentinel-core/statistic/base/bucket_leap_array.cc
  sentinel-core/statistic/base/stat_config_manager.cc
  sentinel-core/statistic/node/cluster_node.cc
  sentinel-core/transport/command/handler/get_switch_status_handler.cc
  sentinel-core/transport/command/http_command_center.cc
  sentinel-core/transport/common/event_loop_thread.cc
Labels: kind/enhancement

#15 Add back LogSlot to default slot chain
  sentinel-core/slot/global_slot_chain.cc
  sentinel-core/slot/global_slot_chain.h
Labels: kind/enhancement

#16 Update README.md
  README.md
Labels: area/document

#17 Add version command handler
  sentinel-core/transport/command/BUILD
  sentinel-core/transport/command/handler/BUILD
  sentinel-core/transport/command/handler/version_handler.cc
  sentinel-core/transport/command/handler/version_handler.h
  sentinel-core/transport/command/http_server_init_target.cc
Labels: kind/enhancement

#18 Refactor the code and fix some bug
  BUILD
  WORKSPACE
  bazel/copts.bzl
  bazel/third_party_repositories.bzl
  examples/json/BUILD
  examples/json/nlohmann_json_example.cc
  sentinel-core/common/entry_result.cc
  sentinel-core/config/local_config.h
  sentinel-core/flow/flow_rule_manager.cc
  sentinel-core/log/logger.h
  sentinel-core/property/BUILD
  sentinel-core/property/dynamic_sentinel_property.h
  sentinel-core/public/sph_u.cc
  sentinel-core/slot/global_slot_chain.cc
  sentinel-core/slot/global_slot_chain.h
  sentinel-core/transport/command/handler/BUILD
  sentinel-core/transport/command/handler/fetch_cluster_node_handler.cc
  sentinel-core/utils/macros.h
  third_party/nlohmann/BUILD
  third_party/nlohmann/json.hpp
Labels: kind/bug, kind/enhancement
